title: Deep Trident Decomposition Network for Single License Plate Image Glare Removal
description: Bo-Hao Chen, Shiting Ye, Jia-Li Yin, Hsiang-Yin Cheng, and Dewang Chen
theme: jekyll-theme-slate
show_downloads: false
